version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: kuafor_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: kuafor_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432"
    networks:
      - app-dev-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d kuafor_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: kuafor_app
    restart: unless-stopped
    env_file:
      - ./backend/.env.development
    environment:
      DB_HOST: db
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "1000"   # ts-node'un algılaması için conteynır içinde değişiklikleri
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-dev-network
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/logs:/app/logs
      - ./backend/uploads:/app/uploads
    working_dir: /app

  # nginx:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   container_name: appointment-hairstyler-system-nginx-dev
  #   restart: always
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
  #   volumes:
  #     - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
  #   networks:
  #     - app-dev-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: kuafor_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@kuafor.com
      PGADMIN_DEFAULT_PASSWORD: password123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    networks:
      - app-dev-network
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  app-dev-network:
    driver: bridge