version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    container_name: kuafor_postgres_test
    environment:
      POSTGRES_DB: kuafor_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres_test_data:/var/lib/postgresql/data
    networks:
      - test-network

  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    container_name: kuafor_backend_test
    depends_on:
      - postgres-test
    networks:
      - test-network

volumes:
  postgres_test_data:

networks:
  test-network:
    driver: bridge