version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: real-estate-dev-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: real-estate-dev-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-dev-network
    ports:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d real-estate-dev-db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: real-estate-dev-backend
    restart: unless-stopped
    env_file:
      - ./.env.development
    environment:
      DB_HOST: db
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "1000"   # ts-node'un algılaması için conteynır içinde değişiklikleri
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-dev-network
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: real-estate-dev-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    networks:
      - app-dev-network
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  app-dev-network:
    driver: bridge