import { Router } from 'express';
import { requireStaffOrAdmin } from '../middleware/authMiddleware';
import * as appointmentController from '../controllers/appointmentController';
const router = Router();
router.get('/', requireStaffOrAdmin, appointmentController.getAppointments);
router.post('/', requireStaffOrAdmin, appointmentController.createAppointment);
router.get('/calendar', requireStaffOrAdmin, appointmentController.getCalendarAppointments);
router.get('/:id', requireStaffOrAdmin, appointmentController.getAppointmentById);
router.put('/:id/status', requireStaffOrAdmin, appointmentController.updateAppointmentStatus);
export default router; 