import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
// PrimeReact CSS (theme + core + icons)
import "primereact/resources/themes/lara-light-blue/theme.css";
import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr">
      <body
        className={`${geistSans.variable} antialiased`}
      >
        {/* Geist Fontu yüklenecek */}
        {children}
      </body>
    </html>
  );
}
