module.exports = (sequelize: any, DataTypes: any) => {
  const ListingsProperty = sequelize.define('ListingsProperty', {
    id: { type: DataTypes.UUID, defaultValue: DataTypes.UUIDV4, primaryKey: true },
    tenant_id: { type: DataTypes.UUID, allowNull: false },
    title: { type: DataTypes.TEXT, allowNull: false },
    description: { type: DataTypes.TEXT },
    price: { type: DataTypes.DECIMAL(14,2), allowNull: false },
    type: { type: DataTypes.ENUM('Satılık','Kiralık'), allowNull: false },
    category: { type: DataTypes.ENUM('Daire','Müstakil','Villa','Ofis','Dükkan','Arsa'), allowNull: false },
    area: { type: DataTypes.INTEGER },
    rooms_label: { type: DataTypes.TEXT },
    bedrooms: { type: DataTypes.SMALLINT },
    bathrooms: { type: DataTypes.SMALLINT },
    floor: { type: DataTypes.SMALLINT },
    total_floors: { type: DataTypes.SMALLINT },
    age: { type: DataTypes.SMALLINT },
    heating: { type: DataTypes.TEXT },
    furnished: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false },
    parking: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false },
    balcony: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false },
    elevator: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false },
    district_name: { type: DataTypes.TEXT },
    city_name: { type: DataTypes.TEXT },
    full_address: { type: DataTypes.TEXT },
    lat: { type: DataTypes.DECIMAL(10,6) },
    lng: { type: DataTypes.DECIMAL(10,6) },
    district_id: { type: DataTypes.INTEGER },
    city_id: { type: DataTypes.INTEGER },
    contact_name: { type: DataTypes.TEXT },
    contact_phone: { type: DataTypes.TEXT },
    contact_email: { type: DataTypes.TEXT },
    contact_is_agent: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false },
    views: { type: DataTypes.BIGINT, allowNull: false, defaultValue: 0 },
    clicks: { type: DataTypes.BIGINT, allowNull: false, defaultValue: 0 },
    is_featured: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false },
    is_urgent: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false },
    is_new: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false },
    status: { type: DataTypes.ENUM('active','pending','sold','rented','inactive'), allowNull: false, defaultValue: 'active' },
    owner_user_id: { type: DataTypes.UUID },
    expires_at: { type: DataTypes.DATE },
    agent_id: { type: DataTypes.UUID },
    owner_customer_id: { type: DataTypes.UUID },
    created_at: { type: DataTypes.DATE, allowNull: false, defaultValue: DataTypes.NOW },
    updated_at: { type: DataTypes.DATE, allowNull: false, defaultValue: DataTypes.NOW },
    deleted_at: { type: DataTypes.DATE },
  }, {
    tableName: 'properties',
    schema: 'listings',
    timestamps: true,
    paranoid: true,
    createdAt: 'created_at',
    updatedAt: 'updated_at',
    deletedAt: 'deleted_at',
    indexes: [
      { fields: ['tenant_id', 'status'] },
      { fields: ['city_name', 'district_name'] },
      { fields: ['owner_user_id'] },
    ],
  });

  return ListingsProperty;
};


