name: Deploy-to-Prod

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SSH → pull & redeploy
        uses: appleboy/ssh-action@v1.0.3

        env:
          GH_PAT: ${{ secrets.GH_PAT }}

        with:
          host:     ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key:      ${{ secrets.SSH_KEY }}
          port:     22
          envs:     GH_PAT
          script: |
            set -euo pipefail

            APP_DIR="$HOME/appointment-hairstyler-system"     # ↙ tüm işlem buraya

            # İlk kez çalışıyorsak klonla
            if [ ! -d "$APP_DIR/.git" ]; then
              git clone https://${GH_PAT}@github.com/Erenen1/appointment-hairstyler-system.git "$APP_DIR"
            fi

            cd "$APP_DIR"
            git fetch --prune --tags
            git checkout main
            git pull origin main

            # Docker yeniden build & restart
            docker compose -f docker-compose.prod.yml \
              down --remove-orphans
            docker compose -f docker-compose.prod.yml \
              up --build -d

            # Eski, kullanılmayan imajları sil
            docker image prune -f
